= hawkular-btm
:source-language: java

ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular-btm]
image::https://travis-ci.org/hawkular/hawkular-btm.svg?branch=master[Build Status,70,18]
endif::[]

[.lead]
*Hawkular BTM* is the Business Transaction Management module for Hawkular.

The project will provide the capabilities to monitor the flow of a business transaction
instance across servers, tiers, on-premises and in the cloud.


== Documentation

REST API documentation can be generated using *-Pdocgen* profile. +
The doc is generated under *rest/target* folder.

```shell
mvn clean install -Pdocgen
```

== Project Structure

The project is divided into several areas:

[cols=">s,d"]
|=======================
| api |
This module contains the Java interfaces for services and processors, as well as +
the information model for exchanging business transaction information.
| backend |
This folder contains the modules that can be deployed.
| dist |
This module builds a distribution containing a pre-packaged Hawkular server with BTM installed.
| integration |
This folder contains various modules that enable BTM to integrate with other (Hawkular) components.
| processors |
This folder contains the processor implementations that derive higher level information from the raw +
business transaction fragments reported by execution environments.
| repository |
This folder contains repository implementations.
| services |
This folder contains the services provided by BTM.
| tests |
This folder contains the integration tests. (TBD)
|=======================


== License

Hawkular-BTM is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.