= hawkular-btm
:source-language: java

ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular-btm]
image::https://travis-ci.org/hawkular/hawkular-btm.svg?branch=master[Build Status,70,18]
endif::[]

[.lead]
*Hawkular BTM* is the Business Transaction Management (BTM) and Application Performance
Management (APM) module for Hawkular.

The project will provide the capabilities to monitor the flow of a business transaction
instance across servers, tiers, on-premises and in the cloud. It will also enable detailed
performance analysis to be performed of the individual components that make up an
application.

== Build

To build the project, run:

```shell
mvn clean install [ -Ptests,vertx,wildfly ]
```

The optional 'tests' profile will automatically run integration tests within a WildFly instance
configured with Hawkular Bus and BTM.

The optional 'vertx' profile provides integration tests running in a vertx environment.

The optional 'wildfly' profile provides integration tests against the Hawkular BTM REST APIs
running in a WildFly server.

The distribution (a preconfigured version of WildFly with all necessary Hawkular components) can be
found here: _dist/target/hawkular-btm-dist-<version>.zip_.


== Documentation

REST API documentation can be generated using *-Pdocgen* profile. +
The doc is generated under *rest/target* folder.

```shell
mvn clean install -Pdocgen
```

== Project Structure

The project is divided into several areas:

[cols=">s,d"]
|=======================
| api |
This module contains the Java interfaces for services and processors, as well as +
the information model for exchanging business transaction information.
| client |
This folder contains the modules used to collector information from an execution environment.
| dist |
This module builds a distribution containing a pre-packaged Hawkular server with BTM installed.
| processors |
This folder contains the processor implementations that derive higher level information from the raw +
business transaction fragments reported by execution environments.
| server |
This folder contains the modules related to the server.
| services |
This folder contains the services provided by BTM.
| tests |
This folder contains the integration tests.
| ui |
The angularjs based user interface.
|=======================


== License

Hawkular-BTM is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015-2016 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
