= hawkular-btm
:source-language: java

ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular-btm]
image::https://travis-ci.org/hawkular/hawkular-btm.svg?branch=master[Build Status,70,18]
endif::[]

[.lead]
*Hawkular BTM* is the Business Transaction Management module for Hawkular.

The project will provide the capabilities to monitor the flow of a business transaction
instance across servers, tiers, on-premises and in the cloud.


== Documentation

REST API documentation can be generated using *-Pdocgen* profile. +
The doc is generated under *rest/target* folder.

```shell
mvn clean install -Pdocgen
```

== License

Hawkular-BTM is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.