= hawkular-apm
:source-language: java

ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular-apm]
image::https://travis-ci.org/hawkular/hawkular-apm.svg?branch=master[Build Status,70,18]
endif::[]

[.lead]
*Hawkular APM* is the Application Performance Management (APM) module for Hawkular.

The project will provide the capabilities to monitor the flow of invocations
across servers, tiers, on-premises and in the cloud. It will also enable detailed
performance analysis to be performed of the individual components that make up an
application.

== Build

To build the project, run:

```shell
mvn clean install [ -Ptests ]
```

The optional 'tests' profile will automatically run integration tests.

The distribution (a preconfigured version of WildFly with APM installed) can be
found here: _dist/target/hawkular-app-dist-<version>.zip_.


== Documentation

REST API documentation can be generated using *-Pdocgen* profile. +
The doc is generated under *rest/target* folder.

```shell
mvn clean install -Pdocgen
```

== Project Structure

The project is divided into several areas:

[cols=">s,d"]
|=======================
| api |
This module contains the Java interfaces for services and processors, as well as +
the information model for exchanging business transaction information.
| client |
This folder contains the modules used to collector information from an execution environment.
| dist |
This module builds a distribution containing a pre-packaged Hawkular server with BTM installed.
| processors |
This folder contains the processor implementations that derive higher level information from the raw +
business transaction fragments reported by execution environments.
| server |
This folder contains the modules related to the server.
| tests |
This folder contains the integration tests.
| tools |
This folder contains the tools for working for APM.
| ui |
The angularjs based user interface.
|=======================


== License

Hawkular-APM is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015-2016 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
